name: Cron Schedule 3 hr Test Java API Server Build on Debian

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  buildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:  Build Java API Server
        id: build_java_api_server
        run: |
          docker build --tag sezing-java-api-server \
            --build-arg "GITHUB_REPO_OWNER=bryan-nice" \
            --build-arg "BRANCH=${GITHUB_HEAD_REF}" \
            .github/workflows/docker/senzing-ci-cd-deb-test-builder
      - name: Slack Notification
        id: slack_notification
        uses: bryan-nice/slack-notification@1.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci-cd-dev
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'Failed to build on GitHub Commit SHA ${{ github.sha }}'
          SLACK_MESSAGE: 'Failed to build on GitHub Commit SHA ${{ github.sha }}'
          SLACK_USERNAME: senzing-api-server
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
