name: Cron Schedule 3 hr Test Java API Server Build on Debian

on:
  push:
    branches:
      - issue-125.bryan-nice
#  schedule:
#    - cron: '0 */3 * * *'

jobs:
  buildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Environment Variables
        run: printenv
      - name: Install base packages
        run: |
          sudo apt update \
          && sudo apt install -y sqlite
      - name: Install G2 Engine
        run: |
          export SENZING_REPO_URL="https://senzing-production-apt.s3.amazonaws.com/senzingrepo_1.0.0-1_amd64.deb" \
          && wget ${SENZING_REPO_URL} \
          && sudo apt-get -y install ./${SENZING_REPO_URL##*/} \
          && sudo apt-get -y update \
          && rm -rf senzingrepo_1.0.0-1_amd64.deb \
          && sudo apt-get -y install \
            senzingapi
#      - name: Build Java API Server
#        id: build_java_api_server
#        run: |
#          docker build --tag sezing-java-api-server:${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} \
#            --build-arg "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" \
#            --build-arg "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}" \
#            --build-arg "SENZING_REPO_URL=https://senzing-staging-apt.s3.amazonaws.com/senzingstagingrepo_1.0.0-1_amd64.deb" \
#            .github/workflows/docker/ci-cd-debian-build
      - name: Create Jira Issue on Build Failure
        uses: Senzing/git-action-jira-issue-creation@1.0.0
        id: create_jira_issue
        #if: failure()
        env:
          JIRA_API_TOKEN: cZcFSWhTg22Xbu23nhqz53AD #${{ secrets.JIRA_SECRET }}
          JIRA_USERNAME: devopsservice@senzing.com #${{ secrets.JIRA_USERNAME }}
          JIRA_ACCOUNT_URL: ${{ secrets.JIRA_ACCOUNT_URL }}
          JIRA_PROJECT: 'PBF'
          JIRA_ISSUE_TYPE: 'Task'
          JIRA_ISSUE_SUMMARY: 'Failed to build Dedfdfdbid adfadfadsfehfjhfjhgfrsion on GitHub Commit SHA ${{ github.sha }}'
          JIRA_ISSUE_DESCRIPTION: |
            The commit SHA is: _${{ github.sha }}_.

            ${{ steps.build_java_api_server.outputs.build_log }}

