name: Pull Request Test Java API Server Build on Debian

on:
  pull_request:
    branches:
      - master

jobs:
  buildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:  Build Java API Server
        run: docker build --tag sezing-java-api-server .github/workflows/docker/debian
      - name: Create Git Issue on Build Failure
        uses: bryan-nice/git-issue-creation@1.1.1
        id: create_git_issue
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: 'bryan-nice'
          GITHUB_REPO_NAME: 'senzing-api-server'
          GITHUB_ISSUE_TITLE: 'Failed to build on GitHub Commit SHA ${{ github.sha }}'
          GITHUB_ISSUE_BODY: |
            Please review git actions log and trouble shoot the build failure.
            The commit SHA is: _${{ github.sha }}_.
      - name: Slack Notification
        uses: bryan-nice/slack-notification@1.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci-cd-dev
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'Failed to build on GitHub Commit SHA ${{ github.sha }}'
          SLACK_MESSAGE: |
            Failed to build on GitHub Commit SHA ${{ github.sha }}
            Git Issue URL: ${{ steps.create_git_issue.outputs.git_issue_url }}
          SLACK_USERNAME: senzing-api-server
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
