name: Test Java API Server Build With Debian Install

on:
  push:
    branches:
      - issue-105.bryan-nice

#  schedule:
#    - cron: '0 */3 * * *'

jobs:
  buildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:  Build Java API Server
        run: docker build --tag sezing-java-api-server .github/workflows/docker/debian
      - name: Slack Notification
        uses: bryan-nice/slack-notification@1.0.2
        if: failure()
        env:
          SLACK_CHANNEL: playground
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'FAILURE'
          SLACK_MESSAGE: 'Fialed to build GitHub SHA ${{ github.sha }}'
          SLACK_USERNAME: senzing-api-server
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
