name: Test Debian Build

on:
  push:
    branches:
      - master

jobs:
  buildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - name: Build Java API Server
        uses: actions/checkout@v1
        run: docker build --tag sezing-java-api-server .github/build/debian