name: Test Debian Build

on:
  push:
    branches:
      - master

jobs:
  buildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - name: Build Java API Server
        run: docker build --tag sezing-java-api-server .github/build/debian
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        if: failure()
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'test'
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'